In [1]:
import csv
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy


In [2]:
dataset1 = pd.read_csv('kaggle_train.csv')
dataset2 = pd.read_csv('kaggle_test.csv')

for column in dataset1.columns:
    dataset1[column].fillna(dataset1[column].mode()[0], inplace=True)

for column in dataset2.columns:
    dataset2[column].fillna(dataset2[column].mode()[0], inplace=True)
                            
x=dataset1.iloc[:,1:42].values
A=dataset2.iloc[:,1:42].values
print(x)
x1 = copy.deepcopy(x)

[[44.0 'Travel_Rarely' 1376.0 ... 6 0 15.0]
 [25.0 'Non-Travel' 675.0 ... 5 0 7.0]
 [57.0 'Travel_Rarely' 210.0 ... 0 0 3.0]
 ...
 [36.0 'Travel_Rarely' 1456.0 ... 2 0 15.0]
 [23.0 'Travel_Rarely' 885.0 ... 2 0 15.0]
 [31.0 'Travel_Frequently' 754.0 ... 8 0 11.0]]


In [3]:
# from sklearn.impute import SimpleImputer
# imuter= SimpleImputer(missing_values=np.nan, strategy='mean')
# imuter.fit(x[:,0,2,6,7,10,13,14,17,22,25,28,30,34,35,37,40])#using the fit function of simple imputer class to fit our imputer on the dataset.
# x[:,0,2,6,7,10,13,14,17,22,25,28,30,34,35,37,40]=imuter.transform(x[:,0,2,6,7,10,13,14,17,22,25,28,30,34,35,37,40])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3,5,9,11,15,16,31])], remainder='passthrough')
ft = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3,5,9,11,15,16,31])], remainder='passthrough')
# for column in x.columns:
#     x[column].fillna(x[column].mean(), inplace=True)

# # for column in dataset2.columns:
# #     dataset2[column].fillna(dataset2[column].mean(), inplace=True)

x = np.array(ct.fit_transform(x))
A = np.array(ft.fit_transform(A))
# fitting and transformer the initial data set and then converting it into a numpy array.

In [4]:
# for column in dataset1.columns:
#     dataset1[column].fillna(dataset1[column].mode()[0], inplace=True)

# for column in dataset2.columns:
#     dataset2[column].fillna(dataset2[column].mode()[0], inplace=True)

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [6]:
from sklearn.preprocessing import LabelEncoder 
Y = dataset1.iloc[:,-2].values
print(Y)


[1 0 0 ... 1 0 1]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, Y, test_size = 0.2, random_state = 0)

In [8]:
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors=5,algorithm='ball_tree',p=2)
# classifier.fit(X_train,y_train)

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators =550, criterion = 'gini', random_state = 0, oob_score='TRUE')
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=550, oob_score='TRUE', random_state=0)

In [10]:
y_pred = classifier.predict(X_test)
y_array= (np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(y_array)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.metrics import roc_auc_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
acc = accuracy_score(y_test,y_pred)
ac123=acc
print(acc)

[[211   0]
 [ 29   6]]
0.8821138211382114


In [12]:
y_final=classifier.predict_proba(x)[:,1]
print(y_final)

[0.63636364 0.1        0.06909091 ... 0.72909091 0.05636364 0.70363636]


In [13]:
# list2=[]
# for i in y_final[0]:
#     list2.append(i[0])
# # print(list2)
# y_pred_att=np.array(list2)
# # print(y_pred_att)
y_pred_att=np.round_(y_final,decimals=2)
print(y_pred_att)

[0.64 0.1  0.07 ... 0.73 0.06 0.7 ]


In [14]:
Final_submission={
    'Attrition': y_pred_att
}
df=pd.DataFrame(Final_submission)
print(df)

      Attrition
0          0.64
1          0.10
2          0.07
3          0.05
4          0.90
...         ...
1225       0.73
1226       0.04
1227       0.73
1228       0.06
1229       0.70

[1230 rows x 1 columns]


In [15]:
df.to_csv('Final_submission.csv')